function Ped_Start = importpedstart(filename)

%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Alexandre\Dropbox\Stages\Stanford\alex-jackrabbot\toy\1\static\ped_file.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/05/26 14:43:25

%% Initialize variables.

delimiter = ',';
startRow = 2;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
orig = dataArray{:, 1};
dest = dataArray{:, 2};
start_frame = dataArray{:, 3};
velocity = dataArray{:, 4};
class1 = dataArray{:, 5};
Ped_Start = [orig dest start_frame velocity class1];

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;

end

